// @refresh reset
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { gql, useQuery } from "@apollo/client";
import { initializeApollo, addApolloState } from "../lib/apolloClient";
import { GetStaticPaths, GetStaticProps } from 'next'
import { ALL_PRODUCTS_QUERY } from '../utils/graphql/queries'

// components
import Products from '../components/Products'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  const { loading, error, data } = useQuery(ALL_PRODUCTS_QUERY);
    if(loading){return <div>Loading...</div>}
      if(error){console.log(error?.networkError)}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"/>
      </Head>

      <main className="container-fluid text-center">
        <h1 className="display-1">
          Welcome to nextjs-vendure-ecommerce!
        </h1>

        <div className="container mx-auto">
          <Products productsData={data} />
        </div>

      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
    const apolloClient = initializeApollo();
  
    await apolloClient.query({
      query: ALL_PRODUCTS_QUERY,
    });
  
    return addApolloState(apolloClient, {
      props: {},
    });
  }


export default Home
